export const actions = {
	SUBMIT_ATTEMPT: 'SUBMIT_ATTEMPT',
	SUBMIT_SUCCESS: 'SUBMIT_SUCCESS',
	SUBMIT_FAILURE: 'SUBMIT_FAILURE',
	REGISTER_FIELD: 'REGISTER_FIELD',
	UNREGISTER_FIELD: 'UNREGISTER_FIELD',
	SET_FIELD_VALUE: 'SET_FIELD_VALUE',
	SET_FIELD_TOUCHED: 'SET_FIELD_TOUCHED',
	SET_ERRORS: 'SET_ERRORS',
	SET_FIELD_ERROR: 'SET_FIELD_ERROR',
	REMOVE_FIELD_ERROR: 'REMOVE_FIELD_ERROR'
};
